### ISSUE TITLE
Don't panic when e.g. piping to `head`

### ISSUE THREAD

**Issue by gabebw** [gabebw/candle#12]
Here's an example:

```
 $ curl --silent daringfireball.net | candle 'html {html}' | head
<html class="daringfireball-net" lang="en">
  <head>
    <meta charset="UTF-8"></meta>
    <title>
      Daring Fireball
    </title>
    <meta name="viewport" content="width=500, minimum-scale=0.45"></meta>
    <link href="/graphics/apple-touch-icon.png" rel="apple-touch-icon-precomposed"></link>
    <link href="/graphics/favicon.ico?v=005" rel="shortcut icon"></link>
    <link rel="mask-icon" href="/graphics/dfstar.svg" color="#4a525a"></link>
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:792:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

The issue is the message shown at the end:

```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:792:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by gabebw** [comment]
Related issue: https://github.com/rust-lang/rust/issues/46016
